var GAME_LEVELS = [
["                                                                                                                    ",
 "                                                                                                                    ",
 "                                                                                                                    ",
 "                                                                                                                    ",
 "                                                                                                                    ",
 "                                                                                                                    ",
 "                                                                                                                    ",
 "                                                                                                                    ",
 "                                                                                                                    ",
 "  x                                                                                                                 ",
 "  x                                                                                                                 ",
 "  x@                                                                                                                ",
 "  xxxx                                                                                                              ",
 "  xxxx                                                                                                              ",
 "  xxxx                                                                 o                                            ",
 "  xxxx          xxxx                                                 xxxx                                           ",
 "  xxxx          xxxx     o    o    o                                 xxxx             o    o    o       oo          ",
 " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!xxxxxxxxxxxxxxxx!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   ",
 "                                                      x!!!!x              x!!!!x                                    ",
 "                                                      xxxxxx              xxxxxx                                    ",
 "                                                                                                                    ",
 "                                                                                                                    ",
 "                                                                                                                    "],
["                                                       x                                                                                    ",
 "  x                                                    x                                                                                    ",
 "  x                                             o  o   x                                                                                    ",
 "  x  @                             o     o      xxxxxxxx                                                                                    ",
 "  xxxxxxxxxx                     xxxxxxxxxx                                                                                                 ",
 "                    o                                                                                                                       ",
 "                 xxxxxxxx                                                                                                                   ",
 "                                                                                                                                            ",
 "                                                                                                                                            ",
 "             o                    o                       o                                                                                 ",
 "         xxxxxxxxxx           xxxxxxxxxxx            xxxxxxxx                                                                               ",
 "                                                                                                                                            ",
 "                                                                                                                                            ",
 "                                                                                                                                            ",
 "                                                                                                                                  o         ",
 "                                                                                            o                         o       xxxxxxxx      ",
 "            o                                                                   o        xxxxxx        o            xxxxxx           x      ",
 "        xxxxx                           o                                     xxxxx                 xxxxxxx                          x      ",
 "                      o                 xxx                                                                                          x      ",
 "    x!!!!!!!!!!!xxxxxxxxxxxxx!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x      ",
 "    xxxxxxxxxxxxx           x!!!!x                         x!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x      ",
 "                            xxxxxx                         x!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x      ",
 "                                                           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      ",
 "                                                                                                                                            ",
 "                                                                                                                                            ",
 "                                                                                                                                            "],
["                                                                                                                                               ",
 "                                                                                                                                               ",
 "                                                                                                                                               ",
 "                                                                                                                                               ",
 "                                     xxxxx       xxxxx   xxxxx                                                                                 ",
 "                                                                                                                                               ",
 "        xxxxxxxxxxxx!!xxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxx                                                                    ",
 "                   x!!x          x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x         x                                                                    ",
 "                   xxxx          x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x         x                                                                    ",
 "                                 x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x         xxxxxxxxxxxxxxxxxxxx!!!!!!!!xxxxx!!!!!!!xxxxxxxxxxxxxxxxxx       xx  ",
 "                                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                            x!!!!!!!!xxxxx!!!!!!!x                xx      xx  ",
 "                                                                                             xxxxxxxxxxxxxxxxxxxxxx                x       xx  ",
 "                                                                                                                                   x       xx  ",
 "                                                                                                                                   x       xx  ",
 "                                                                                                                                   x      xxx  ",
 "                                                                                                                                           xx  ",
 "                                               xxxxxxx                                                                                     xx  ",
 "                                                                                                                                          xxx  ",
 "                              xxxxx                                 xxxxxxx                           xxxxxxx       xxxx                   xx  ",
 "                                                                                                                            xxxxxxxxxxxxxxxxx  ",
 " x      xxxxxxx   xxxx                     xxxxxx                        xxxxx               xxxxxx                                            ",
 " x                                                                                                                                             ",
 " x                                                                                                                                             ",
 " x                                                                                                                                             ",
 " x                                                                                                                                             ",
 " x                                        xxxx                                                                                                 ",
 " x                                                                                                                                             ",
 " xxxxxxxxxxxxx!!!!!!!!!xxxxx!!!!!!xxxx!!!!!!!!!!!xxx!!!!!!!!xxxxxx!!!!!!!!!!!xxxxxx!!!!!xxxx!!!!!!!xxxxxx!!!!!!!xxxxxxxxxx!!!!!!!!!xxxxxxxxxx  ",
 "             x!!!!!!!!!xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx  ",
 "             x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx  ",
 "             x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx  ",
 "             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
 "                                                                                                                                               ",
 "                                                                                                                                               "],
];

 if (typeof module != "undefined" && module.exports)
   module.exports = GAME_LEVELS;
